# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.8
loader_version=0.19.5
kotlin_loader_version=1.13.6+kotlin.2.2.20
# Mod Properties
mod_version=9.4
maven_group=org.nguhroutes
archives_base_name=nguhroutes
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.136.1+1.21.8
